    name: CommandAliases
  version: 2.0.0
  api: [1.12.0, 1.13.0, 1.0.0]
  main: applqpak\CommandAliases\CommandAliases
  commands:
    cmdalias:
      description: "Adds a Command Alias to any Command!"
      usage: "/cmdalias <alias> <command>"
      permission: cmdalias.run
